// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy.Data.Configurations;

#nullable disable

namespace Pharmacy.Data.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pharmacy.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "compras@farmaciacentro.com",
                            Name = "Farmacia del Centro"
                        },
                        new
                        {
                            Id = 2,
                            Email = "compras@hospitalsanrafael.com",
                            Name = "Hospital San Rafael"
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Dispatcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dispatchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Laura",
                            LastName = "Gómez",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Carlos",
                            LastName = "Reyes",
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 2 },
                            Status = 1
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.FulfillmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FulfilledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("FulfillmentEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FulfilledAtUtc = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Type = "Created"
                        },
                        new
                        {
                            Id = 2,
                            FulfilledAtUtc = new DateTime(2026, 6, 21, 15, 30, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Type = "Shipped"
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStock = 120,
                            ProductId = 1,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 }
                        },
                        new
                        {
                            Id = 2,
                            CurrentStock = 8,
                            ProductId = 2,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 2 }
                        },
                        new
                        {
                            Id = 3,
                            CurrentStock = 45,
                            ProductId = 3,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 3 }
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Laboratories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contacto@labpisa.com",
                            Name = "Laboratorios Pisa"
                        },
                        new
                        {
                            Id = 2,
                            Email = "contacto@sanofi.com",
                            Name = "Grupo Sanofi"
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DispatcherId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DispatcherId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedUtc = new DateTime(2026, 6, 21, 15, 30, 0, 0, DateTimeKind.Utc),
                            CreatedUtc = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            DispatcherId = 1,
                            Priority = 0,
                            Status = 1,
                            TotalPrice = 180.90m
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2026, 7, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            DispatcherId = 2,
                            Priority = 1,
                            Status = 0,
                            TotalPrice = 210.00m
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Units = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Units = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Units = 1
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Dose")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PrincipalActive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("Batch", "ExpirationDate");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Batch = "PZ-1001",
                            CommercialName = "Paracetamol Max",
                            Dose = 500,
                            ExpirationDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryId = 1,
                            LaboratoryId = 1,
                            Price = 45.50m,
                            PrincipalActive = "Paracetamol"
                        },
                        new
                        {
                            Id = 2,
                            Batch = "PZ-1002",
                            CommercialName = "Amoxil",
                            Dose = 250,
                            ExpirationDate = new DateTime(2027, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryId = 2,
                            LaboratoryId = 1,
                            Price = 89.90m,
                            PrincipalActive = "Amoxicilina"
                        },
                        new
                        {
                            Id = 3,
                            Batch = "SF-2001",
                            CommercialName = "Lipitor",
                            Dose = 20,
                            ExpirationDate = new DateTime(2028, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InventoryId = 3,
                            LaboratoryId = 2,
                            Price = 210.00m,
                            PrincipalActive = "Atorvastatina"
                        });
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.FulfillmentEvent", b =>
                {
                    b.HasOne("Pharmacy.Data.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("Pharmacy.Data.Entities.Product", "Product")
                        .WithOne("InventoryItem")
                        .HasForeignKey("Pharmacy.Data.Entities.InventoryItem", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Order", b =>
                {
                    b.HasOne("Pharmacy.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacy.Data.Entities.Dispatcher", "Dispatcher")
                        .WithMany()
                        .HasForeignKey("DispatcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Dispatcher");
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.OrderLine", b =>
                {
                    b.HasOne("Pharmacy.Data.Entities.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacy.Data.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Product", b =>
                {
                    b.HasOne("Pharmacy.Data.Entities.Laboratory", "Laboratory")
                        .WithMany("Medicines")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Laboratory", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Pharmacy.Data.Entities.Product", b =>
                {
                    b.Navigation("InventoryItem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
